apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: smaysmay73/api:latest 
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              value: mongodb://angova-mongodb-headless:27017/angovadb
            - name: SALT_KEY
              value: "azertyuiopAZERTUIOP"
            